version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - peakiq-network

  llm_engine:
    build:
      context: ./llm_engine
    ports:
      - "8001:8001"
    networks:
      - peakiq-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - peakiq-network

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8080:80"
    networks:
      - peakiq-network
    depends_on:
      - backend

networks:
  peakiq-network:
    driver: bridge