version: '3.8'

services:
  backend:
    image: python:3.9
    container_name: peakiq-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - llm_engine

  llm_engine:
    image: huggingface/transformers-pytorch-cpu
    container_name: peakiq-llm
    
    # Additional setup for the model will go here:

  redis:
    image: redis:latest
    container_name: peakiq-redis
    ports:
      - "6379:6379"

  dashboard:
    image: nginx:alpine
    container_name: peakiq-dashboard

    # Configuration for serving the dashboard will go here: